
# name: 部署文档

# on:
#   push:
#     branches:
#       # 确保这是你正在使用的分支名称
#       - main

# jobs:
#   deploy-gh-pages:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           # 如果你文档需要 Git 子模块，取消注释下一行
#           # submodules: true


#       - name: 安装 pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 7
#           run_install: true


#       - name: 设置 Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: pnpm

#       - name: 安装依赖
#         run: pnpm install --frozen-lockfile

#       - name: 构建文档
#         env:
#           NODE_OPTIONS: --max_old_space_size=8192
#         run: |-
#           pnpm run docs:build
#           > cosarty_blog/.vuepress/dist/.nojekyll

#       - name: 部署文档
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           # 这是文档部署到的分支名称
#           branch: gh-pages
#           folder: cosarty_blog/.vuepress/dist
name: deploy to aliyun

on:
  push:
    branches: ['master']

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      # npm install and build
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
        env:
          CI: true
      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build
         # > cosarty_blog/.vuepress/dist/.nojekyll
      # Deploy to aliyun
      - name: 部署到阿里服务器
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "cosarty_blog/.vuepress/dist/"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/html/
